service: cv-website-local-api

provider:
  name: aws
  runtime: nodejs22.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  environment:
    TELEGRAM_BOT_TOKEN: ${env:TELEGRAM_BOT_TOKEN, ''}
    TELEGRAM_CHAT_ID: ${env:TELEGRAM_CHAT_ID, ''}

functions:
  form:
    handler: lambda/form/index.handler
    timeout: 20
    events:
      - httpApi:
          path: /form
          method: any

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    noPrependStageInUrl: true
